spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master-postservice.yaml

  data:
    redis:
      host: localhost
      port: 6379
      channels:
        user_ban_channel:
          name: user_ban
        notification_like_channel:
          name: notification_like_channel
        comment_channel:
          name: comment_channel
        like_post_channel:
          name: like_channel
      cache:
        default-ttl: 3600
        users:
          name: users
        authors:
          name: authors
        posts:
          name: posts
        comments:
          name: comments
        feed:
          name: feed
        settings:
          max-feed-size: 5
          max-post-comments-size: 5


    kafka:
      port: 9092
      host: localhost
      group-id: account_service

      post-likes:
        name: post-likes
      comment-likes:
        name: comment-likes
      posts:
        name: posts
      comments:
        name: comments
      post-views:
        name: post-views
      topics:
        topic-settings:
          comments:
            name: comment
          comment-likes:
            name: comment-like
          post-likes:
            name: post-like
          posts:
            name: post
          post-views:
            name: post-view
server:
  port: 8091

user-service:
  host: localhost
  port: 8090

post:
  moderator:
    threads-count: 20

async:
  corePoolSize: 5
  maxPoolSize: 10
  queueCapacity: 100

services:
  s3:
    bucket-name: user-service-bucket
    endpoint: http://127.0.0.1:9000
    accessKey: user
    secretKey: password
    isMocked: false
    targetWidth: 1080
    targetHeight: 566
    maxFilesAmount: 10

logging:
  level:
    root: info

scheduled:
  author-banner: "@daily"

limits:


api:
  path: /api/v1