spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: localhost
      port: 6379
      channels:
        user_ban_channel:
          name: user_ban
        notification_like_channel:
          name: notification_like_channel
        post_channel:
          name: post_channel

  mvc:
    servlet:
      path: /api/v1

server:
  port: 8081

authservice:
  host: localhost
  port: 9090
user-service:
  host: localhost
  port: 8090

logging:
  level:
    root: info

scheduled:
  author-banner: "@daily"

limits:
  unverified_post_limit: 5