spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        pending_operation_channel:
          name: pending-operation-channel

feign:
  openExchangeRatesClient:
    url: https://openexchangerates.org/api
    appId: ca800d6c1f28496a9461bd842d20b919