spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master-achievementservice.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        comment_channel:
          name: comment_channel
        follower_channel:
          name: follower_channel
        like_channel:
          name: like_channel
        achievement_channel:
          name: follower_channel

async:
  corePoolSize: 8
  maxPoolSize: 10
  queueCapacity: 1000
  threadNamePrefix: "task-executor-thread-"

server:
  port: 8093

logging:
  level:
    root: info

achievements:
  title:
    love_everyone: love_everyone
    expert: EXPERT
    blogger: BLOGGER